<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends ServiceEntityRepository
{


    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Article::class);
    }

    public function getArticlesInHomepage()
    {
        $qb = $this->createQueryBuilder('a')
            ->setMaxResults(Article::ARTICLES_IN_HOMEPAGE)
            ->orderBy('a.id', 'desc');

        return $qb->getQuery()->getResult();
    }


    public function getArticles($page, $nbPerPage)
    {

        $queryBuilder = $this->createQueryBuilder('a')
            ->orderBy('a.id', 'desc');

        $query = $queryBuilder->getQuery();
        $query
            // On définit l'annonce à partir de laquelle commencer la liste
            ->setFirstResult(($page - 1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage);

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($query, true);


    }
}
