# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$zX08DrjjdmQ/jMsT8p924u0uGStwgmQYb80S.ftols0NHfY2G0x3K
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout_on_user_change : true

            http_basic: ~
            provider: our_db_provider

            logout:
                path: /logout
                target: /

    access_control:
             # require ROLE_USER for /admin*
             - { path: ^/admin, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        #Symfony\Component\Security\Core\User\User:
            #algorithm: bcrypt
            #cost: 12


             # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
